apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - image: iiacrplayground.azurecr.io/todo-api:0.0.1
          name: todo-api
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: todo-api-config
            - secretRef:
                name: todo-api-secrets
          ports:
            - containerPort: 8000
              name: api
